import test from 'node:test';
import assert from 'node:assert/strict';
import * as sim from '../src/simulation.js';
import {lifeStage} from '../src/characters.js';
import {generateIsland} from '../src/island-generator.js';
import {createProject} from '../src/settlements.js';
const step=(g,n,random)=>{for(let i=0;i<n;i++)sim.tick(g,1,random);};
function startBirth(){const g=sim.createGame();g.objects.push({id:'nursery',type:'nursery',x:-6,z:4,rotation:0});assert.equal(sim.enqueue(g,'incubate','nursery').ok,true);step(g,25);assert.equal(g.incubations.length,1);return g;}
function hatch(g){g.incubations[0].due=(g.day-1)*1440+g.minute+1;step(g,1);return Object.values(g.npcs).find(n=>n.age<1);}
test('configured racial inheritance is used when a newborn hatches',()=>{const g=sim.createGame();g.config.prayer.racialInheritanceRate=50;g.config.prayer.racialInheritanceStdDev=0;g.config.prayer.racialMutationInheritanceChance=100;g.player.prayer.radiance=20;g.player.prayer.mutations=['crown'];g.objects.push({id:'nursery',type:'nursery',x:-6,z:4,rotation:0});assert.equal(sim.enqueue(g,'incubate','nursery').ok,true);step(g,25);const baby=hatch(g);assert.equal(baby.prayer.radiance,10);assert.deepEqual(baby.prayer.mutations,['crown']);});
test('adult prepares an incubation, pays once and a named infant joins the live roster',()=>{const g=startBirth();assert.equal(g.money,2100);const baby=hatch(g);assert.ok(baby);assert.equal(Array.from(baby.name).length,2);assert.doesNotMatch(baby.name,/^星芽 \d+$/);assert.equal(baby.parents[0].uid,g.player.uid);assert.equal(lifeStage(baby.age),'infant');assert.equal(g.incubations.length,0);assert.equal(Object.keys(g.npcs).length,5);assert.deepEqual(sim.restore(sim.serialize(g)),g);});
test('pregnancy rejects minors, occupied pods and insufficient funds without charging',()=>{const g=startBirth();assert.equal(sim.enqueue(g,'incubate','nursery').ok,false);g.incubations=[];g.player.age=10;assert.equal(sim.enqueue(g,'incubate','nursery').ok,false);g.player.age=28;g.money=299;assert.equal(sim.enqueue(g,'incubate','nursery').ok,false);assert.equal(g.money,299);});
test('incubation freezes on pause and an occupied pod cannot be sold',()=>{const g=startBirth(),due=g.incubations[0].due;assert.equal(sim.sellItem(g,'nursery'),false);g.speed=0;step(g,100);assert.equal(g.incubations[0].due,due);assert.equal(g.incubations.length,1);});
test('infants stay in their cradle and adult AI tends hungry infants',()=>{const g=startBirth(),baby=hatch(g);baby.needs.hunger=10;const pos={x:baby.x,z:baby.z};step(g,90);assert.ok(baby.needs.hunger>50);assert.equal(baby.x,pos.x);assert.equal(baby.z,pos.z);assert.equal(baby.queue.length,0);});
test('old age removes NPC from actions and keeps a memorial exactly once',()=>{const g=sim.createGame();sim.enqueue(g,'chat','zig');g.npcs.zig.age=120;step(g,1);assert.equal(g.npcs.zig,undefined);assert.equal(g.queue.some(q=>q.targetId==='zig'),false);assert.equal(g.memorials[0].cause,'old_age');step(g,2);assert.equal(g.memorials.length,1);assert.deepEqual(sim.restore(sim.serialize(g)),g);});
test('a deceased parent passes personal cash proceeds to the living child',()=>{const g=sim.createGame(),parent=g.npcs.nova,child=g.npcs.pip;for(const n of Object.values(g.npcs))n.ai.enabled=false;child.parents=[{uid:parent.uid,name:parent.name}];parent.money=942;parent.inventory={spores:0,mushrooms:0};parent.age=120;step(g,1);assert.equal(g.npcs.nova,undefined);assert.equal(child.money,942);assert.deepEqual(child.inventory,{spores:0,mushrooms:0});assert.deepEqual(sim.restore(sim.serialize(g)),g);});
test('a deceased main parent passes the household estate to the living child',()=>{const g=sim.createGame(),child=g.npcs.pip,successor=g.npcs.zig;for(const n of Object.values(g.npcs))n.ai.enabled=false;child.parents=[{uid:g.player.uid,name:g.player.name}];g.money=1141;g.harvest={spores:0,mushrooms:0};g.player.age=120;step(g,1);assert.equal(g.player.alive,true);assert.equal(g.player.uid,successor.uid);assert.equal(g.money,successor.money);assert.equal(child.money,1141);assert.deepEqual(child.inventory,{spores:0,mushrooms:0});});
test('a deceased main automatically controls the oldest living resident',()=>{const g=sim.createGame(),deadUid=g.player.uid,successor=structuredClone(g.npcs.zig);for(const n of Object.values(g.npcs))n.ai.enabled=false;g.npcs.nova.age=40;g.npcs.lumi.age=55;g.npcs.pip.age=12;g.player.age=120;step(g,1);assert.equal(g.player.alive,true);assert.equal(g.player.uid,successor.uid);assert.equal(g.player.name,successor.name);assert.equal(g.npcs.zig,undefined);assert.equal(g.speed,0);assert.ok(g.memorials.some(n=>n.uid===deadUid));});
test('a deceased switched main also falls back to the oldest remaining resident',()=>{const g=sim.createGame();assert.equal(sim.switchControl(g,'nova').ok,true);const deadUid=g.player.uid,successorUid=g.npcs.zig.uid;for(const n of Object.values(g.npcs))n.ai.enabled=false;g.player.age=120;step(g,1);assert.equal(g.player.alive,true);assert.equal(g.player.uid,successorUid);assert.equal(g.controlledId,'player');assert.equal(g.npcs.nova,undefined);assert.ok(g.memorials.some(n=>n.uid===deadUid));});
test('a child receives starter funds when reaching adulthood before paying for meals alone',()=>{const g=sim.createGame(),child=g.npcs.pip;sim.setAutonomy(g,false);for(const n of Object.values(g.npcs))n.ai.enabled=n===child;g.config.time.starYearDays=1;child.age=17.999;child.money=0;child.needs={...child.needs,hunger:10};step(g,1,()=>0);assert.ok(child.age>=18);assert.equal(child.money,600);assert.equal(child.queue[0]?.type,'eat');});
test('control can switch to any living resident and return without losing either profile',()=>{const g=sim.createGame(),kaiUid=g.player.uid,novaUid=g.npcs.nova.uid;assert.equal(sim.switchControl(g,'nova').ok,true);assert.equal(g.controlledId,'nova');assert.equal(g.player.uid,novaUid);assert.equal(g.npcs.kai.uid,kaiUid);assert.equal(sim.switchControl(g,'kai').ok,true);assert.equal(g.controlledId,'kai');assert.equal(g.player.uid,kaiUid);assert.equal(g.npcs.nova.uid,novaUid);assert.deepEqual(sim.restore(sim.serialize(g)).player,g.player);});
test('new residents are autonomous and switching control keeps autonomy enabled',()=>{const g=sim.createGame();assert.equal(g.autonomy.enabled,true);assert.ok(Object.values(g.npcs).every(n=>n.ai.enabled));assert.equal(sim.switchControl(g,'nova').ok,true);assert.equal(g.autonomy.enabled,true);assert.equal(g.player.ai.enabled,true);assert.equal(sim.switchControl(g,'kai').ok,true);assert.equal(g.autonomy.enabled,true);assert.equal(g.npcs.nova.ai.enabled,true);});
test('version 9 saves without a control tab still restore to the original player',()=>{const g=sim.createGame();delete g.controlledId;const restored=sim.restore(sim.serialize(g));assert.equal(restored.controlledId,'player');assert.equal(restored.player.uid,'kai');});
test('legacy saves keep an existing population above the current island capacity',()=>{
 const g=sim.createGame();g.version=23;g.civilization.discoveryPath=['home','spore','city'];g.civilization.visits.city=1;g.civilization.surveys.city=0;g.civilization.surveyDays.city=0;
 for(let i=0;i<13;i++){const id=`legacy-extra-${i}`,n=structuredClone(g.npcs.pip);n.id=id;n.uid=id;n.name=`额外居民${i}`;g.npcs[id]=n;}
 for(const [id,n] of Object.entries(g.npcs)){n.relationships={};for(const other of Object.keys(g.npcs))if(other!==id)n.relationships[other]=20;g.relationships[id]=20;}
 assert.equal(Object.keys(g.npcs).length,17);assert.equal(sim.restore(sim.serialize(g)).version,24);
});
test('starvation warns before death and food resets exposure',()=>{const g=sim.createGame(),successorUid=g.npcs.zig.uid;g.needs.hunger=0;g.player.starvation=719;step(g,1);assert.equal(g.player.alive,true);assert.ok(g.log.some(l=>l.text.includes('饥饿')));g.needs.hunger=60;step(g,1);assert.equal(g.player.starvation,0);g.needs.hunger=0;g.player.starvation=1439;step(g,1);assert.equal(g.player.alive,true);assert.equal(g.player.uid,successorUid);assert.equal(g.speed,0);assert.equal(g.memorials[0].cause,'starvation');assert.equal(sim.enqueue(g,'walk',null,{x:1,z:1}).ok,true);});
test('takeover preserves the successor identity, skills, needs and family while cleaning old targets',()=>{const g=sim.createGame();g.npcs.nova.skills.science=12;const uid=g.npcs.nova.uid;g.player.alive=false;assert.equal(typeof sim.takeOver,'function');assert.equal(sim.takeOver(g,'nova').ok,true);assert.equal(g.player.uid,uid);assert.equal(g.player.name,'诺瓦');assert.equal(g.skills.science,12);assert.equal(g.npcs.nova,undefined);assert.equal(g.player.alive,true);assert.equal(g.speed,0);assert.deepEqual(sim.restore(sim.serialize(g)),g);});
test('pending child retains parent identity when the parent dies before hatching',()=>{const g=startBirth(),uid=g.player.uid,successorUid=g.npcs.zig.uid;g.player.age=120;step(g,1);assert.equal(g.player.uid,successorUid);g.speed=1;const baby=hatch(g);assert.equal(baby.parents[0].uid,uid);assert.notEqual(baby.parents[0].uid,g.player.uid);assert.deepEqual(sim.restore(sim.serialize(g)),g);});
test('birth and memorial records reject corrupt save data',()=>{const g=startBirth();g.incubations[0].due='tomorrow';assert.throws(()=>sim.restore(sim.serialize(g)));});
test('NPC autonomously starts a planned birth when resources and caregivers are ready',()=>{const g=sim.createGame();g.objects.push({id:'nursery',type:'nursery',x:-6,z:4,rotation:0});for(const n of Object.values(g.npcs))for(const k in n.needs)n.needs[k]=95;g.npcs.nova.familyDesire=1;step(g,40,()=>0);assert.equal(g.incubations.length,1);assert.notEqual(g.incubations[0].parents[0].uid,g.player.uid);assert.ok(g.log.some(l=>l.text.includes('自主决定')));});
test('AI defers births when funds, health, cooldown or childcare capacity are inadequate',()=>{assert.equal(typeof sim.birthDecision,'function');const g=sim.createGame();g.objects.push({id:'nursery',type:'nursery',x:-6,z:4,rotation:0});const p=g.npcs.nova;for(const k in p.needs)p.needs[k]=95;g.money=599;assert.equal(sim.birthDecision(g,'nova').ready,false);g.money=2400;p.needs.hunger=20;assert.equal(sim.birthDecision(g,'nova').ready,false);p.needs.hunger=95;p.lastBirthDay=g.day;assert.equal(sim.birthDecision(g,'nova').ready,false);p.lastBirthDay=null;p.age=95;assert.equal(sim.birthDecision(g,'nova').ready,false);});
test('main character fertility choices obey autonomy toggle and never overdraw shared resources',()=>{const g=sim.createGame();g.objects=g.objects.filter(o=>o.type!=='sofa');g.objects.push({id:'nursery',type:'nursery',x:-6,z:4,rotation:0});for(const n of Object.values(g.npcs))n.familyDesire=0;for(const k in g.needs)g.needs[k]=95;g.player.familyDesire=1;sim.setAutonomy(g,false);step(g,2,()=>0);assert.equal(g.queue.some(q=>q.type==='incubate'||q.source==='ai'),false);sim.setAutonomy(g,true);step(g,20,()=>0);assert.equal(g.incubations[0].parents[0].uid,g.player.uid);assert.equal(g.money,2100);assert.equal(sim.birthDecision(g,'player').ready,false);});
test('offspring mix both parents appearance and interests without inheriting trained skills',()=>{assert.equal(typeof sim.inheritTraits,'function');const a={color:'#ff0000',genome:{...sim.createGame().player.genome,stature:.9,build:.9,head:1,antenna:1},preferences:{science:0,research:20},familyDesire:.2},b={color:'#0000ff',genome:{...sim.createGame().player.genome,stature:1.1,build:1.1,head:1.1,antenna:1.2},preferences:{dance:20},familyDesire:.8};const baby=sim.inheritTraits([a,b],()=>.5);assert.equal(baby.color,'#800080');assert.equal(baby.genome.stature,1);assert.equal(baby.preferences.research,10);assert.equal(baby.preferences.dance,10);assert.equal(baby.familyDesire,.5);assert.deepEqual(baby.mutations,[]);});
test('newborn names use a large unique two-character alien-name combination space',()=>{const used=[],names=new Set();for(let i=0;i<40;i++){const name=sim.generateResidentName({uid:`name-${i}`,preferences:{research:20,observe:12}},used);assert.equal(Array.from(name).length,2);assert.match(name,/^[\u4e00-\u9fff]{2}$/u);used.push(name);names.add(name);}assert.equal(names.size,40);});
test('legacy placeholder newborn names migrate once and remain stable',()=>{const g=startBirth(),baby=hatch(g);baby.name='星芽 647';const restored=sim.restore(sim.serialize(g)),name=restored.npcs[baby.uid].name;assert.equal(Array.from(name).length,2);assert.doesNotMatch(name,/^星芽 \d+$/);assert.equal(sim.restore(sim.serialize(restored)).npcs[baby.uid].name,name);});
test('rare mutation alters one inherited appearance gene and stays bounded',()=>{assert.equal(typeof sim.inheritTraits,'function');const p=sim.createGame().player;const baby=sim.inheritTraits([p],()=>0,{color:0,stature:100,build:0,head:0,antenna:0});assert.deepEqual(baby.mutations,['身高变异']);assert.notDeepEqual(baby.genome,p.genome);assert.ok(baby.genome.stature<=1.2);});
test('two consenting adult friends in the social graph snapshot racial attributes at incubation',()=>{const g=sim.createGame();g.player.prayer.radiance=4;g.player.prayer.mutations=['crown'];g.npcs.nova.prayer.nether=6;g.npcs.nova.prayer.mutations=['spines'];g.relationships.nova=75;g.objects.push({id:'nursery',type:'nursery',x:-6,z:4,rotation:0});assert.equal(sim.enqueue(g,'incubate','nursery',undefined,'nova').ok,true);step(g,25);assert.equal(g.incubations[0].parents.length,2);assert.deepEqual(g.incubations[0].parents.map(p=>p.prayer),[g.player.prayer,g.npcs.nova.prayer]);const baby=hatch(g);assert.equal(baby.parents.length,2);assert.equal(baby.skills.science,0);assert.ok(baby.genome);const restored=sim.restore(sim.serialize(g));assert.deepEqual(restored.npcs[baby.uid].genome,baby.genome);assert.equal(restored.npcs[baby.uid].color,baby.color);});
test('newborn cradle is placed on clear ground beside the incubator instead of inside its solid base',()=>{const g=startBirth(),baby=hatch(g),pod=g.objects.find(o=>o.id==='nursery');assert.ok(Math.hypot(baby.x-pod.x,baby.z-pod.z)>=1.8);});
test('a second parent dying before the incubation action completes cancels the queued birth cleanly',()=>{const g=sim.createGame();g.relationships.nova=75;g.objects.push({id:'nursery',type:'nursery',x:-6,z:4,rotation:0});sim.enqueue(g,'incubate','nursery',undefined,'nova');g.npcs.nova.age=120;step(g,1);assert.equal(g.queue.some(q=>q.type==='incubate'),false);assert.equal(g.money,2400);assert.deepEqual(sim.restore(sim.serialize(g)),g);});
test('AI does not enlist a co-parent who already has two children',()=>{const g=sim.createGame();g.objects.push({id:'nursery',type:'nursery',x:-6,z:4,rotation:0});for(const k in g.needs)g.needs[k]=95;g.relationships.nova=90;g.memorials=[{uid:'a',name:'A',age:10,day:1,cause:'starvation',parents:[{uid:g.npcs.nova.uid,name:'诺瓦'}]},{uid:'b',name:'B',age:11,day:1,cause:'starvation',parents:[{uid:g.npcs.nova.uid,name:'诺瓦'}]}];assert.notEqual(sim.birthDecision(g,'player').partnerId,'nova');});
test('mutation at an inherited gene boundary still makes a visible change',()=>{const p=sim.createGame().player;p.genome.stature=1.2;const values=[0,.3,1];const child=sim.inheritTraits([p],()=>values.shift());assert.notEqual(child.genome.stature,p.genome.stature);});

function readyFamily(){const g=sim.createGame();g.objects.push({id:'nursery',type:'nursery',x:-6,z:4,rotation:0});for(const k in g.config.needDecay)g.config.needDecay[k]=0;for(const p of [g.player,...Object.values(g.npcs)])p.familyDesire=1;for(const needs of [g.needs,...Object.values(g.npcs).map(n=>n.needs)])for(const k in needs)needs[k]=95;for(const id in g.relationships)g.relationships[id]=0;for(const n of Object.values(g.npcs))for(const id in n.relationships)n.relationships[id]=0;return g;}
test('autonomous birth prioritizes the most friendly eligible second parent and permits single parent only without one',()=>{const g=readyFamily();assert.equal(sim.birthDecision(g,'player').partnerId,null);g.relationships.nova=60;g.relationships.zig=80;assert.equal(sim.birthDecision(g,'player').partnerId,'zig');g.npcs.zig.lastBirthDay=g.day;assert.equal(sim.birthDecision(g,'player').partnerId,'nova');g.npcs.nova.parents=[{uid:g.player.uid,name:g.player.name}];assert.equal(sim.birthDecision(g,'player').partnerId,null);});
test('NPC autonomous birth can choose the controlled resident and preserves that parent after a control switch',()=>{let g=readyFamily();g.relationships.nova=75;assert.equal(sim.birthDecision(g,'nova').partnerId,g.player.uid);sim.switchControl(g,'nova');assert.equal(sim.enqueue(g,'incubate','nursery',undefined,'kai').ok,true);g.queue[0].source='ai';sim.switchControl(g,'kai');g=sim.restore(sim.serialize(g));g.autonomy.enabled=false;for(const n of Object.values(g.npcs))n.ai.enabled=false;g.npcs.zig.ai.enabled=true;g.npcs.lumi.ai.enabled=true;step(g,25,()=>.5);assert.equal(g.incubations.length,1);assert.deepEqual(g.incubations[0].parents.map(p=>p.uid),['nova','kai']);});
test('queued autonomous single-parent birth upgrades to two parents when an eligible partner becomes available',()=>{const g=readyFamily();assert.equal(sim.enqueue(g,'incubate','nursery').ok,true);g.queue[0].source='ai';g.relationships.nova=75;g.autonomy.enabled=false;for(const n of Object.values(g.npcs))n.ai.enabled=false;g.npcs.zig.ai.enabled=true;g.npcs.lumi.ai.enabled=true;step(g,25,()=>.5);assert.equal(g.incubations.length,1);assert.deepEqual(g.incubations[0].parents.map(p=>p.uid),['kai','nova']);assert.match(g.log.map(l=>l.text).join(' '),/与诺瓦共同自主决定/);});

test('population capacity grows only with landed islands and both birth paths respect it',async()=>{
 const {populationCapacity}=await import('../src/civilization.js');const g=readyFamily();
 for(let i=0;i<3;i++){const p=structuredClone(g.npcs.pip);p.uid=`extra-${i}`;g.npcs[p.uid]=p;}
 assert.equal(populationCapacity(g),8);assert.match(sim.birthDecision(g,'player').reason,/人口上限 8/);assert.equal(sim.enqueue(g,'incubate','nursery').ok,false);
 g.civilization.observations=3;g.wonders.archive=3;assert.equal(populationCapacity(g),8);
 g.civilization.visits.spore=1;assert.equal(populationCapacity(g),16);assert.equal(sim.birthDecision(g,'player').ready,true);assert.equal(sim.enqueue(g,'incubate','nursery').ok,true);g.queue=[];
 g.space.backs.spore=true;g.civilization.visits.spore=20;g.civilization.discoveryPath=['home','spore'];assert.equal(populationCapacity(g),16);const island=generateIsland(g.civilization.seed,0);g.civilization.islands[island.id]=island;g.civilization.discoveryPath.push(island.id);g.civilization.visits[island.id]=1;g.civilization.surveys[island.id]=0;g.civilization.surveyDays[island.id]=0;g.civilization.projects[island.id]=createProject(g.civilization.seed);assert.equal(populationCapacity(g),24);
 for(let i=3;i<11;i++){const p=structuredClone(g.npcs.pip);p.uid=`extra-${i}`;g.npcs[p.uid]=p;}
 for(const id of Object.keys(g.npcs)){g.relationships[id]??=0;for(const [other,n]of Object.entries(g.npcs))if(other!==id)n.relationships[id]??=0;}
 assert.equal(sim.enqueue(g,'incubate','nursery').ok,true);assert.equal(populationCapacity(sim.restore(sim.serialize(g))),24);
});
